### ISSUE TITLE
src\network\websocket.ts 文件应该大写成这样：src\network\webSocket.ts

### ISSUE THREAD

**Issue by dong-lufei** [galaxy-s10/billd-live#2]
不然运行报错：

```
App running at:
- Local:   http://localhost:8000/
- Network: http://192.168.31.87:8000/

ERROR in ./src/store/network/index.ts:4:32
TS1261: Already included file name 'E:/test/billd-live/src/network/webSocket.ts' differs from file name 'E:/test/billd-live/src/network/websocket.ts' only in casing.
  The file is in the program because:
    Imported via '@/network/webSocket' from file 'E:/test/billd-live/src/store/network/index.ts'
    Imported via './webSocket' from file 'E:/test/billd-live/src/network/webRtc.ts'
    Root file specified for compilation
    2 |
    3 | import { WebRTCClass } from '@/network/webRtc';
  > 4 | import { WebSocketClass } from '@/network/webSocket';
      |                                ^^^^^^^^^^^^^^^^^^^^^
    5 |
    6 | type NetworkRootState = {
    7 |   wsMap: Map<string, WebSocketClass>;
```

**Comment by dong-lufei** [comment]
输入房间名，点开始直播没反应，控制台报错：
WebSocket connection to 'ws://localhost:4300/socket.io/?EIO=4&transport=websocket' failed:

**Comment by galaxy-s10** [comment]
> 输入房间名，点开始直播没反应，控制台报错： WebSocket connection to 'ws://localhost:4300/socket.io/?EIO=4&transport=websocket' failed:

这个得搭配后端：https://github.com/galaxy-s10/billd-live-server

**Comment by galaxy-s10** [comment]
> 不然运行报错：
> 
> ```
> App running at:
> - Local:   http://localhost:8000/
> - Network: http://192.168.31.87:8000/
> 
> ERROR in ./src/store/network/index.ts:4:32
> TS1261: Already included file name 'E:/test/billd-live/src/network/webSocket.ts' differs from file name 'E:/test/billd-live/src/network/websocket.ts' only in casing.
>   The file is in the program because:
>     Imported via '@/network/webSocket' from file 'E:/test/billd-live/src/store/network/index.ts'
>     Imported via './webSocket' from file 'E:/test/billd-live/src/network/webRtc.ts'
>     Root file specified for compilation
>     2 |
>     3 | import { WebRTCClass } from '@/network/webRtc';
>   > 4 | import { WebSocketClass } from '@/network/webSocket';
>       |                                ^^^^^^^^^^^^^^^^^^^^^
>     5 |
>     6 | type NetworkRootState = {
>     7 |   wsMap: Map<string, WebSocketClass>;
> ```

fixed
