### ISSUE TITLE
使用canvas代替video是否是必要呢

### ISSUE THREAD

**Issue by twelvet-s** [galaxy-s10/billd-live#4]
canvas的渲染久了感觉网页一卡一卡的，使用video也可以做到的直播素材渲染吧

**Comment by twelvet-s** [comment]
> > canvas的渲染久了感觉网页一卡一卡的，使用video也可以做到的直播素材渲染吧
> 
> 浏览器需要混流推流时得用canvas，但是只需要拉流的话，不用canvas也行。
> 
> > 有些点播场景，如果用video直接渲染，可以右键调倍速；用canvas渲染可以避免这个情况。

我看了b站的实现是用的video，它是使用的div去添加素材，我觉得研究这块比较合适，怎么实现的混流(捕获那块区域啥的或者有其他的使用)。直接采用canvas性能可能比较低，这块我自己研究一下先。
点播这块加速可以做理论上可以禁止的，这个没必要前端禁止，真要加速完全可以拿到直播流去自己播放。但还是谢谢啦

**Comment by galaxy-s10** [comment]
> > > canvas的渲染久了感觉网页一卡一卡的，使用video也可以做到的直播素材渲染吧
> > 
> > 
> > 浏览器需要混流推流时得用canvas，但是只需要拉流的话，不用canvas也行。
> > > 有些点播场景，如果用video直接渲染，可以右键调倍速；用canvas渲染可以避免这个情况。
> 
> 我看了b站的实现是用的video，它是使用的div去添加素材，我觉得研究这块比较合适，怎么实现的混流(捕获那块区域啥的或者有其他的使用)。直接采用canvas性能可能比较低，这块我自己研究一下先。 点播这块加速可以做理论上可以禁止的，这个没必要前端禁止，真要加速完全可以拿到直播流去自己播放。但还是谢谢啦

应该是创建了一个canvas，然后再将canvas的stream设置到video；或者是直接录制外层的dom。个人偏向是第一种

**Comment by twelvet-s** [comment]
> > > > canvas的渲染久了感觉网页一卡一卡的，使用video也可以做到的直播素材渲染吧
> > > 
> > > 
> > > 浏览器需要混流推流时得用canvas，但是只需要拉流的话，不用canvas也行。
> > > > 有些点播场景，如果用video直接渲染，可以右键调倍速；用canvas渲染可以避免这个情况。
> > 
> > 
> > 我看了b站的实现是用的video，它是使用的div去添加素材，我觉得研究这块比较合适，怎么实现的混流(捕获那块区域啥的或者有其他的使用)。直接采用canvas性能可能比较低，这块我自己研究一下先。 点播这块加速可以做理论上可以禁止的，这个没必要前端禁止，真要加速完全可以拿到直播流去自己播放。但还是谢谢啦
> 
> 应该是创建了一个canvas，然后再将canvas的stream设置到video；或者是直接录制外层的dom。个人偏向是第一种

我也认同你的第一个说法，把dom转流，但不播放就不会觉得页面卡了
