### ISSUE TITLE
媒体流需要在关闭素材的时候进行关闭，不然会卡顿

### ISSUE THREAD

**Issue by twelvet-s** [galaxy-s10/billd-live#6]
在关闭视频，音频等素材的时候应该关闭读取他们的流
liveStreamingMaterial.videoStream!.getTracks().forEach(track => {
    track.stop();
});

**Comment by twelvet-s** [comment]
应使用requestAnimationFrame(renderAll)代替定时器改善性能

**Comment by galaxy-s10** [comment]
todo

**Comment by galaxy-s10** [comment]
> 在关闭视频，音频等素材的时候应该关闭读取他们的流 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });

其实现在本质上就只有一个stream，里面有一个音频轨和视频轨，不需要关闭。

**Comment by twelvet-s** [comment]
> > 在关闭视频，音频等素材的时候应该关闭读取他们的流 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });
> 
> 其实现在本质上就只有一个stream，里面有一个音频轨和视频轨，不需要关闭。

在删除窗口素材的时候，浏览器窗口的流没有关闭

**Comment by twelvet-s** [comment]
> > > 在关闭视频，音频等素材的时候应该关闭读取他们的流 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });
> > 
> > 
> > 其实现在本质上就只有一个stream，里面有一个音频轨和视频轨，不需要关闭。
> 
> 在删除窗口素材的时候，浏览器窗口的流没有关闭

![1694843118114](https://github.com/galaxy-s10/billd-live/assets/31510505/4a7dcb45-4c8b-414a-bfa6-91ac32b2fe1a)

**Comment by galaxy-s10** [comment]
> > > > 在关闭视频，音频等素材的时候应该关闭读取他们的流 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });
> > > 
> > > 
> > > 其实现在本质上就只有一个stream，里面有一个音频轨和视频轨，不需要关闭。
> > 
> > 
> > 在删除窗口素材的时候，浏览器窗口的流没有关闭
> 
> ![1694843118114](https://user-images.githubusercontent.com/31510505/268431230-4a7dcb45-4c8b-414a-bfa6-91ac32b2fe1a.jpg)

这个好像没有对应的回调，b站的效果和我的一样

**Comment by twelvet-s** [comment]
> > > > > 在关闭视频，音频等素材的时候应该关闭读取他们的流 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });
> > > > 
> > > > 
> > > > 其实现在本质上就只有一个stream，里面有一个音频轨和视频轨，不需要关闭。
> > > 
> > > 
> > > 在删除窗口素材的时候，浏览器窗口的流没有关闭
> > 
> > 
> > ![1694843118114](https://user-images.githubusercontent.com/31510505/268431230-4a7dcb45-4c8b-414a-bfa6-91ac32b2fe1a.jpg)
> 
> 这个好像没有对应的回调，b站的效果和我的一样

b站是有关闭的，就像保存dom节点一样保存创建出来的窗口流，关闭的时候执行这个就行了
liveStreamingMaterial.videoStream!.getTracks().forEach(track => {
track.stop();
});

**Comment by galaxy-s10** [comment]
> > > > > > 在关闭视频，音频等素材的时候应该关闭读取他们的流 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });
> > > > > 
> > > > > 
> > > > > 其实现在本质上就只有一个stream，里面有一个音频轨和视频轨，不需要关闭。
> > > > 
> > > > 
> > > > 在删除窗口素材的时候，浏览器窗口的流没有关闭
> > > 
> > > 
> > > ![1694843118114](https://user-images.githubusercontent.com/31510505/268431230-4a7dcb45-4c8b-414a-bfa6-91ac32b2fe1a.jpg)
> > 
> > 
> > 这个好像没有对应的回调，b站的效果和我的一样
> 
> b站是有关闭的，就像保存dom节点一样保存创建出来的窗口流，关闭的时候执行这个就行了 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });

点击素材列表里面的x来删除，可以关闭，但是你点击顶部的那个停止共享，我没看到有没有对应的回调

**Comment by twelvet-s** [comment]
> > > > > > > 在关闭视频，音频等素材的时候应该关闭读取他们的流 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });
> > > > > > 
> > > > > > 
> > > > > > 其实现在本质上就只有一个stream，里面有一个音频轨和视频轨，不需要关闭。
> > > > > 
> > > > > 
> > > > > 在删除窗口素材的时候，浏览器窗口的流没有关闭
> > > > 
> > > > 
> > > > ![1694843118114](https://user-images.githubusercontent.com/31510505/268431230-4a7dcb45-4c8b-414a-bfa6-91ac32b2fe1a.jpg)
> > > 
> > > 
> > > 这个好像没有对应的回调，b站的效果和我的一样
> > 
> > 
> > b站是有关闭的，就像保存dom节点一样保存创建出来的窗口流，关闭的时候执行这个就行了 liveStreamingMaterial.videoStream!.getTracks().forEach(track => { track.stop(); });
> 
> 点击素材列表里面的x来删除，可以关闭，但是你点击顶部的那个停止共享，我没看到有没有对应的回调

可能理解错了，不是点击那个共享关闭，是点删除素材这个停止共享要取消点对应的
