### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialJC-T** [galaxy-s10/billd-live#7]
hi，我们这边是 [蓝桥云课](www.lanqiao.cn)，是一家做在线教育的网站，有兴趣将您的课程上线到我们平台进行销售推广吗，合作详情可点击 https://www.lanqiao.cn/questions/503610/ 了解，期待您的联系～

**Comment by galaxy-s10** [comment]
> hi，我们这边是 [蓝桥云课](www.lanqiao.cn)，是一家做在线教育的网站，有兴趣将您的课程上线到我们平台进行销售推广吗，合作详情可点击 https://www.lanqiao.cn/questions/503610/ 了解，期待您的联系～

考虑考虑
