### ISSUE TITLE
浏览器页面不可见或者被覆盖时，canvas就停止渲染了，请问要怎么继续推流

### ISSUE THREAD

**Issue by zhp0710** [galaxy-s10/billd-live#8]
浏览器页面不可见或者被覆盖时，canvas就停止渲染了，请问要怎么继续推流

**Comment by galaxy-s10** [comment]
用了worker，没有这个问题

**Comment by zhp0710** [comment]
我用setInterval每20ms执行canvas.renderAll可以实现，没用worker，但这个是不是很耗资源
